from crewai import Agent, Crew, Process, Task


def build_reels_crew():
    intake_coordinator = Agent(
        role="Intake Coordinator",
        goal="Validate the incoming video job and produce a clean processing manifest.",
        backstory=(
            "You prepare video processing jobs for downstream agents. "
            "You reject incomplete inputs, standardize metadata, and define the job plan."
        ),
        verbose=True,
    )

    transcription_analyst = Agent(
        role="Transcription Analyst",
        goal="Turn long-form video into a structured transcript with useful content analysis.",
        backstory=(
            "You review transcription output and identify topic shifts, hooks, "
            "emotion spikes, and quote-worthy moments."
        ),
        verbose=True,
    )

    clip_strategist = Agent(
        role="Clip Strategist",
        goal="Select the most promising reel candidates from the transcript.",
        backstory=(
            "You optimize for short-form retention. You prefer moments that stand "
            "alone, start strong, and remain understandable without full-video context."
        ),
        verbose=True,
    )

    reframing_agent = Agent(
        role="Reframing Director",
        goal="Define how each selected clip should be reframed for vertical video.",
        backstory=(
            "You understand mobile-first composition. You keep the speaker or subject "
            "prominent and avoid crops that lose important visual context."
        ),
        verbose=True,
    )

    qa_delivery_agent = Agent(
        role="QA and Delivery Manager",
        goal="Approve only clips that meet quality standards and deliver them to Google Drive.",
        backstory=(
            "You verify technical quality, naming consistency, caption readability, "
            "and delivery completeness before marking the job done."
        ),
        verbose=True,
    )

    intake_task = Task(
        description=(
            "Validate the video job input. Produce a normalized manifest containing: "
            "input video path or URL, requested output count, clip length range, "
            "style profile, branding settings, and Google Drive folder ID."
        ),
        expected_output="A clean job manifest in JSON.",
        agent=intake_coordinator,
    )

    transcription_task = Task(
        description=(
            "Use the transcript generated by the transcription toolchain and produce "
            "a structured analysis with timestamped segments, topic changes, hooks, "
            "high-energy moments, and quote-worthy passages."
        ),
        expected_output="Transcript analysis JSON with timestamps and clip signals.",
        agent=transcription_analyst,
    )

    clip_selection_task = Task(
        description=(
            "Choose the top 3 to 5 clip candidates from the analyzed transcript. "
            "For each clip, return start time, end time, score, title, and a short "
            "reason it is likely to perform well as a reel."
        ),
        expected_output="Ranked clip list with timestamps and performance rationale.",
        agent=clip_strategist,
    )

    reframing_task = Task(
        description=(
            "For each selected clip, define the framing strategy for a 9:16 output. "
            "Specify whether to use face tracking, dynamic crop, split composition, "
            "or fallback center crop."
        ),
        expected_output="A reframing plan for each selected clip.",
        agent=reframing_agent,
    )

    qa_delivery_task = Task(
        description=(
            "Review the processed clips after cutting, reframing, captioning, and export. "
            "Approve only clips that meet duration, framing, caption, and audio quality "
            "requirements. Prepare the upload package for Google Drive."
        ),
        expected_output="Final approval report with upload-ready assets and delivery metadata.",
        agent=qa_delivery_agent,
    )

    return Crew(
        agents=[
            intake_coordinator,
            transcription_analyst,
            clip_strategist,
            reframing_agent,
            qa_delivery_agent,
        ],
        tasks=[
            intake_task,
            transcription_task,
            clip_selection_task,
            reframing_task,
            qa_delivery_task,
        ],
        process=Process.sequential,
        verbose=True,
    )


if __name__ == "__main__":
    crew = build_reels_crew()
    result = crew.kickoff(
        inputs={
            "input_video": "https://youtube.com/watch?v=example",
            "output_count": 4,
            "clip_length_min": 30,
            "clip_length_max": 60,
            "style_profile": "podcast_reels",
            "google_drive_folder_id": "drive_folder_123",
        }
    )
    print(result)
